# -*- coding: utf-8 -*-
[core]
name = Mamulique
level = dialect
macroareas = 
	North America
iso639-3 = emm
hid = emm
countries = 
	MX
timespan = 1855-01-01/1855-01-01

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Mamulique (emm-emm) = 10 (Extinct).

