# -*- coding: utf-8 -*-
[core]
name = Atauro
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:195-202 **hh:hvw:Hull:Timor:Austronesian** **hh:hv:Edwards:Rote-Meto:2021**:77-86
subrefs = 
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

