# -*- coding: utf-8 -*-
[core]
name = Ná-Meo
hid = neo
level = language
iso639-3 = neo
latitude = 22.4189
longitude = 106.435
macroareas = 
	Eurasia
countries = 
	VN
links = 
	https://www.wikidata.org/entity/Q15977293
	https://en.wikipedia.org/wiki/N%C3%A1-Meo_language

[altnames]
glottolog = 
	Na-Meo
multitree = 
	Ná-Meo
	Viet Nam
lexvo = 
	Ná-Meo [en]
hhbib_lgcode = 
	Na Meo
	Na Meo (Cao Bang)
	Na Meo (Tuyen Quang)

[identifier]
multitree = neo

[endangerment]
status = threatened
source = E29
date = 2026-03-17T11:25:25
comment = Ná-Meo (neo-neo) = 6b (Threatened). Language of recognized ethnic group: Hmong.

[classification]
sub = **hh:vw:Hsiu:Na-Meo**
subrefs = 
	**hh:vw:Hsiu:Na-Meo**

[sources]
glottolog = 
	**hh:ew:Nguyen:Mieu**
	**hh:vw:Hsiu:Na-Meo**

