# -*- coding: utf-8 -*-
[core]
name = Varendri
level = dialect
latitude = 24.3745
longitude = 88.6042
macroareas = 
	Eurasia
countries = 



[altnames]
multitree = 
	Northern Bengali
glottolog = 
	Northern Bengali

[identifier]
multitree = ben-nor

