# -*- coding: utf-8 -*-
[core]
name = Asaro'o
hid = mtv
level = language
iso639-3 = mtv
latitude = -5.68263
longitude = 146.508
macroareas = 
	Papunesia
countries = 
	PG
links = 
	https://en.wikipedia.org/wiki/Asaro%27o_language
	https://www.wikidata.org/entity/Q3503684

[sources]
glottolog = 
	**hh:hv:ClaassenMcElhanon:Finisterre**
	**hh:hv:Ross:Voorhoeve**
	**hh:w:Carteretal:Mur**

[altnames]
multitree = 
	Asaro'o
	Morafa
lexvo = 
	Asaro'o [en]
hhbib_lgcode = 
	Morafa

[identifier]
multitree = mtv

[classification]
sub = **hh:w:Carteretal:Mur**
subrefs = 
	**hh:w:Carteretal:Mur**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Asaro’o (mtv-mtv) = 5 (Developing).

