# -*- coding: utf-8 -*-
[core]
name = Sawabantu
level = family
links = 
	https://en.wikipedia.org/wiki/Sawabantu_languages
	https://www.wikidata.org/entity/Q532003

[classification]
sub = **hh:hv:NursePhilippson:Bantu**:170 **hh:hvw:Ebobisse:Sawabantu**:395-404 **hh:hv:Grollemund:Sawabantu**:156
subrefs = 
	**hh:hvw:Ebobisse:Sawabantu**
	**hh:hv:Grollemund:Sawabantu**
	**hh:hv:NursePhilippson:Bantu**

