# -*- coding: utf-8 -*-
[core]
name = Central Caspian
level = language
macroareas = 
	Eurasia
hid = NOCODE_Central-Caspian
countries = 
	IR
longitude = 50.83281
latitude = 36.76562

[altnames]
hhbib_lgcode = 
	Chalus-Ramsar
	Elasht
	Kalārestāq and Kelārdasht
	Kelardasht
	Langa
	Mazanaderani-Tunekabouni
	Ramsar
	Ramsari
	Tonekaboni
	Tonekābon
	Tonekābonī
	Tonekābonī von Šīrūd
	Tonokābon

[classification]
sub = **hh:h:Lecoq:Caspiens** **hh:hvld:Stilo:Tati** **hh:hv:Stilo:Caspian-Tatic** **hh:s:Borjian:Tonekabon**
subrefs = 
	**hh:h:Lecoq:Caspiens**
	**hh:hvld:Stilo:Tati**
	**hh:s:Borjian:Tonekabon**
	**hh:hv:Stilo:Caspian-Tatic**

[endangerment]
status = threatened
source = Glottolog
date = 2026-04-16T10:27:48
comment = Central Caspian (NOCODE_Central-Caspian-NOCODE_Central-Caspian) = 6b (Threatened).

[hh_ethnologue_comment]
comment = The Central Caspian varieties spoken in Ramsar, Tonekabon, Kelardasht and surrounding areas of Mazanderan province are counted as part of the Mazandarani [mzn]
	languages in E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29. However, there is insufficient intelligibility between Central Caspian and other varieties of Mazandarani (**hh:s:Borjian:Tonekabon**:8, **hh:hv:Stilo:Caspian-Tatic**:659-660) to justify this, and consequently, Central Caspian merits its own entry. See also: Mazanderani [mzn].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Central-Caspian

