# -*- coding: utf-8 -*-
[core]
name = Kochic
level = family
links = 
	https://www.wikidata.org/entity/Q6424775
	https://en.wikipedia.org/wiki/Koch_languages

[classification]
sub = **hh:hv:Burling:Bodo-Garo:2012**
subrefs = 
	**hh:hv:Burling:Bodo-Garo:2012**

