# -*- coding: utf-8 -*-
[core]
name = Yasa-Kombe
level = family

[classification]
sub = **hh:hvw:Ebobisse:Sawabantu**:395-404 **hh:h:Guthrie:Bantu-Western**:26 **hh:soc:Belew:Iyasa**:33
subrefs = 
	**hh:hvw:Ebobisse:Sawabantu**
	**hh:h:Guthrie:Bantu-Western**
	**hh:soc:Belew:Iyasa**

