# -*- coding: utf-8 -*-
[core]
name = Rarhi
level = dialect
macroareas = 
	Eurasia
countries = 
latitude = 23.2324
longitude = 87.8615

[altnames]
multitree = 
	Central Bengali
	Central Standard Bengali
glottolog = 
	Central Bengali
	Rarhi

[identifier]
multitree = ben-cen

