# -*- coding: utf-8 -*-
[core]
name = Hokkaido-Kuril Ainu
level = family

[classification]
sub = **hh:h:Janhunen:Ainu**:64-65 **hh:hv:Bugaeva:Ainuic**:561-566
subrefs = 
	**hh:h:Janhunen:Ainu**
	**hh:hv:Bugaeva:Ainuic**

