# -*- coding: utf-8 -*-
[core]
name = Seit-Kaitetu
hid = hik
level = language
iso639-3 = hik
latitude = -3.6111
longitude = 128.068
macroareas = 
	Papunesia
countries = 
	ID
links = 
	https://www.wikidata.org/entity/Q7446989
	https://en.wikipedia.org/wiki/Seit-Kaitetu_language

[sources]
glottolog = 
	**hh:h:Taber:Maluku**
	**hh:hv:Travis:Ambon**
	**hh:hvw:Collins:CMaluku**
	**hh:hw:vanHoevell:Ambonsche**
	**hh:vw:Taufik:Hitu**

[altnames]
multitree = 
	Hila-Kaitetu
	Seit-Kaitetu
lexvo = 
	Seit-Kaitetu [en]
hhbib_lgcode = 
	Hila
	Kaitetu
	Seit

[identifier]
multitree = hik

[classification]
sub = **hh:hvw:Collins:CMaluku** **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:379-439
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hvw:Collins:CMaluku**

[endangerment]
status = moribund
source = E29
date = 2026-03-17T11:25:25
comment = Seit-Kaitetu (hik-hik) = 8a (Moribund).

