# -*- coding: utf-8 -*-
[core]
name = Pannonian Ruthenian
level = dialect
iso639-3 = rsk
hid = rsk
countries = 
	RS
macroareas = 
	Eurasia
links = 
	https://en.wikipedia.org/wiki/Pannonian_Rusyn
	https://www.wikidata.org/entity/Q35660

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Ruthenian (rsk-rsk) = 4 (Educational). Statutory language of provincial identity in Autonomous Province Vodjvodina (2009, Autonomous Province Vodjvodina Statute, Article 26).

[sources]
glottolog = 
	**iso6393:2021-005**

