# -*- coding: utf-8 -*-
[core]
name = Mazanderani-Shahmirzadi
level = family
links = 
	https://www.wikidata.org/entity/Q13356
	https://en.wikipedia.org/wiki/Mazanderani_language

[classification]
sub = **hh:h:Lecoq:Caspiens** **hh:hvld:Stilo:Tati** **hh:hv:Stilo:Caspian-Tatic** **hh:s:Borjian:Tonekabon**
subrefs = 
	**hh:h:Lecoq:Caspiens**
	**hh:hvld:Stilo:Tati**
	**hh:s:Borjian:Tonekabon**
	**hh:hv:Stilo:Caspian-Tatic**

