# -*- coding: utf-8 -*-
[core]
name = Neuchâtelois
level = dialect
macroareas = 
	Eurasia
countries = 
links = 
	https://www.wikidata.org/entity/Q59325083

[altnames]
multitree = 
	Neuchatelais
glottolog = 
	Neuchatelais

[identifier]
multitree = frp-nec

