# -*- coding: utf-8 -*-
[core]
name = Manggaraiic
level = family

[classification]
sub = **hh:hv:Verheijen:Manggarai** **hh:he:Verheijen:Manggarai**:16-21 **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:120-123
subrefs = 
	**hh:hv:Verheijen:Manggarai**
	**hh:he:Verheijen:Manggarai**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

