# -*- coding: utf-8 -*-
[core]
name = Semandang
level = dialect
macroareas = 
	Papunesia
countries = 
	ID
iso639-3 = sdq
hid = sdq

[altnames]
glottolog = 
	Samandang

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Semandang (sdq-sdq) = 5 (Developing).

[sources]
glottolog = 
	**iso6393:2019-043**

