# -*- coding: utf-8 -*-
[core]
name = Bodo-Mech-Kachari
level = family

[classification]
sub = **hh:hv:PostBurling:NEIndia**:225-226 **hh:hv:Burling:Bodo-Garo:2012**
subrefs = 
	**hh:hv:Burling:Bodo-Garo:2012**
	**hh:hv:PostBurling:NEIndia**

