# -*- coding: utf-8 -*-
[core]
name = Magiyi
level = language
iso639-3 = gmg
hid = gmg
countries = 
	PG
macroareas = 
	Papunesia
longitude = 144.88
latitude = -4.88

[classification]
sub = **hh:h:Ethnologue:22**
subrefs = 
	**hh:h:Ethnologue:22**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Magiyi (gmg-gmg) = 6a* (Vigorous).

[sources]
glottolog = 
	**hh:h:Ethnologue:23**
	**hh:h:Ethnologue:24**
	**hh:h:Ethnologue:25**
	**iso6393:2011-022**
	**iso6393:2013-029**
	**langsci:eberhard:simons:etal:ed:20:1**

