# -*- coding: utf-8 -*-
[core]
name = Ruwila
level = dialect
hid = rwl
countries = 
	TZ
macroareas = 
	Africa
iso639-3 = rwl
links = 
	https://en.wikipedia.org/wiki/Ruwila_language
	https://www.wikidata.org/entity/Q105161535

[sources]
glottolog = 
	**iso6393:2017-024**
	**iso6393:2018-087**
	**iso6393:2020-038**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Ruwila (rwl-rwl) = 6a (Vigorous).

