# -*- coding: utf-8 -*-
[core]
name = Graubünden-Grisons
level = dialect
macroareas = 
	Eurasia
countries = 
links = 
	https://www.wikidata.org/entity/Q1020828

[altnames]
multitree = 
	Graubenden-Grisons
	Valserisch
glottolog = 
	Graubenden-Grisons

[identifier]
multitree = gsw-gra

