# -*- coding: utf-8 -*-
[core]
name = Bhutanese Sign Language
level = language
hid = dyl
countries = 
	BT
macroareas = 
	Eurasia
longitude = 89.33058
latitude = 27.48405
links = 
	https://en.wikipedia.org/wiki/Bhutanese_Sign_Language
	https://www.wikidata.org/entity/Q19882346

[sources]
glottolog = 
	**hh:h:Gurung:Bhutanese-Sign**
	**hh:h:Morgan:Southern-Asia**
	**iso6393:2025-004**

[classification]
sub = Minimal information but presumed independent (**hh:h:Gurung:Bhutanese-Sign**)
subrefs = 
	**hh:h:Gurung:Bhutanese-Sign**

[altnames]
hhbib_lgcode = 
	Bhutan: Bhutanese Sign Language

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Bhutanese Sign Language (dyl-dyl) = 5 (Developing). Recognized language (2019, National Policy for Persons with Disabilities), Recognized in a standardized form, advocates early language exposure for deaf children, deaf education in BhSL formally recognized through grade 12 (2023 S. Gurung).

