# -*- coding: utf-8 -*-
[core]
name = Suau chain
level = family

[classification]
sub = **hh:hv:Ross:WMelanesia**:190-212 **hh:hvld:Lithgow:Milne**:461 **hh:hvw:Cooper:Suau**
subrefs = 
	**hh:hvw:Cooper:Suau**
	**hh:hv:Ross:WMelanesia**
	**hh:hvld:Lithgow:Milne**

