# -*- coding: utf-8 -*-
[core]
name = Krevin
level = dialect
macroareas = 
	Eurasia
iso639-3 = zkv
hid = zkv
countries = 
	LV
timespan = 1805-01-01/1805-01-01

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Krevinian (zkv-zkv) = 10 (Extinct).

