# -*- coding: utf-8 -*-
[core]
name = Bima-Lembata
level = family

[classification]
sub = **hh:hvs:Fricke:Flores-Lembata**:229-232 **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:99-105
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hvs:Fricke:Flores-Lembata**

