# -*- coding: utf-8 -*-
[core]
name = Burundi Sign Language
level = dialect
macroareas = 
	Africa
hid = lsb
countries = 
	BI
iso639-3 = lsb
links = 
	https://en.wikipedia.org/wiki/Burundian_Sign_Language
	https://www.wikidata.org/entity/Q105196488

[sources]
glottolog = 
	**iso6393:2010-031**
	**iso6393:2016-024**
	**iso6393:2020-022**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Burundian Sign Language (lsb-lsb) = 5* (Developing).

