# -*- coding: utf-8 -*-
[core]
name = Sula-Buru
level = family
links = 
	https://en.wikipedia.org/wiki/Buru%E2%80%93Sula_languages
	https://www.wikidata.org/entity/Q7636057

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:369-378
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

