# -*- coding: utf-8 -*-
[core]
name = Dadu'a
level = language
latitude = -8.24886
longitude = 125.57585
macroareas = 
	Papunesia
countries = 
	TL
hid = NOCODE_Dadua

[altnames]
multitree = 
	Dadua
glottolog = 
	Dadua
hhbib_lgcode = 
	Dadu'a from Ilimano's central coastal village of Behau
	Timor Dadu'a

[identifier]
multitree = gal-dad

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:195-202 **hh:hvw:Hull:Timor:Austronesian** **hh:hv:Edwards:Rote-Meto:2021**:77-86
subrefs = 
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[endangerment]
status = not endangered
source = Penn
date = 2026-06-01T11:25:25
comment = Dadu'a (NOCODE_Dadua-NOCODE_Dadua) = 6a* (Vigorous).

[hh_ethnologue_comment]
comment = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29 includes Dadu'a, spoken in the center of Atauro island and on the north coast of Timor, in a single language Atauran [adb] comprising the Rasua (Rahesuk), Raklungu (Klu’un Hahan Adabe), Hresuk (Resuk) and Dadu’a varieties. In this, the code [adb] is re-used from an entry that originally referred to a supposed Papuan language of Atauro island. However, Dadu'a is very likely not intelligible to the Rasua, Raklungu and Hresuk (**hh:hvw:Bracks:Atauro**) and thus merits its own entry. See also: Adabe [adb].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Dadua

