# -*- coding: utf-8 -*-
[core]
name = Oninic
level = family

[classification]
sub = **hh:hv:EdwardsGrimes:Eastern-Indonesia** **hh:hv:Kaplan:Onin-Sekar-Uruangnirin**
subrefs = 
	**hh:hv:Kaplan:Onin-Sekar-Uruangnirin**
	**hh:hv:EdwardsGrimes:Eastern-Indonesia**

