# -*- coding: utf-8 -*-
[core]
name = Rasua
level = language
hid = NOCODE_Rasua
countries = 
	TL
macroareas = 
	Papunesia
longitude = 125.60921
latitude = -8.17377

[altnames]
hhbib_lgcode = 
	Beloi
	Bába
	North Atauran

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:195-202 **hh:hvw:Hull:Timor:Austronesian** **hh:hv:Edwards:Rote-Meto:2021**:77-86
subrefs = 
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[endangerment]
status = not endangered
source = BracksandEdwards
date = 2026-06-01T11:25:25
comment = Rasua (NOCODE_Rasua-NOCODE_Rasua) = 6a* (Vigorous).

[hh_ethnologue_comment]
comment = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29 includes Rasua, spoken in the north of Atauro island, in a single language Atauran [adb] comprising the Rasua (Rahesuk), Raklungu (Klu’un Hahan Adabe), Hresuk (Resuk) and Dadu’a varieties. In this, the code [adb] is re-used from an entry that originally referred to a supposed Papuan language of Atauro island. However, Rasua is not intelligible to Raklungu and Hresuk, and likely not to Dadu’a either (**hh:hvw:Bracks:Atauro**) and thus merits its own entry. See also: Adabe [adb].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Rasua

