# -*- coding: utf-8 -*-
[core]
name = Lutos
hid = ndy
level = language
iso639-3 = ndy
latitude = 8.52074
longitude = 19.0071
macroareas = 
	Africa
countries = 
	CF
	TD
links = 
	https://www.wikidata.org/entity/Q6705910
	https://en.wikipedia.org/wiki/Lutos_language

[sources]
glottolog = 
	**eballiso2009:36092**
	**hh:h:Nougayrol:NECAR**
	**hh:he:Modat:Fertyt**
	**hh:phon:Ndoko:Luto**
	**hh:phon:Olson:Lutos**
	**hh:phontyp:Yanguende:Vale-Ndele**
	**hh:phonw:Olson:Nduga**
	**hh:s:Mololi:Ndoka**
	**hh:s:Moundo:Ruto**
	**hh:s:Selezilo:Ndoka**
	**hh:soc:Moehama:Lutos**

[altnames]
multitree = 
	Lutos
	Ruto
lexvo = 
	Lutos [en]
hhbib_lgcode = 
	Luto
	Mvang (Bai/Vanga)
	Ndoka
	Ndoka de Ndélé
	Ndouka
	Nduga
	Ndòkà
	Ruto
	Vale de Ndélé is likely Nduka or Wad Luto (Olson 2024:470)
	Wad

[triggers]
lgcode = 
	baguirmiennes
	lutos
	luto
	ruto
	rito

[identifier]
multitree = ndy

[classification]
sub = **hh:hv:Boyeldieu:Expansion-SBB**
subrefs = 
	**hh:hv:Boyeldieu:Expansion-SBB**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Luto (ndy-ndy) = 5* (Developing).

