# -*- coding: utf-8 -*-
[core]
name = Buhi
level = dialect
iso639-3 = ubl
macroareas = 
	Papunesia
countries = 
	PH
hid = ubl
longitude = 123.5
latitude = 13.17
links = 
	https://en.wikipedia.org/wiki/Buhi%27non_Bikol_language
	https://www.wikidata.org/entity/Q18664494

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Bikol, Buhi’non (ubl-ubl) = 5 (Developing).

[sources]
glottolog = 
	**iso6393:2009-078**

