# -*- coding: utf-8 -*-
[core]
name = Etchemin
level = language
iso639-3 = etc
hid = etc
countries = 
	US
macroareas = 
	North America
timespan = 1605-01-01/1605-01-01

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Etchemin (etc-etc) = 10 (Extinct).

[sources]
glottolog = 
	**hh:hv:Goddard:Eastern-Algonquian**

