# -*- coding: utf-8 -*-
[core]
name = Matambwe
level = dialect
iso639-3 = wtb
hid = wtb
countries = 
	TZ
macroareas = 
	Africa
links = 
	https://en.wikipedia.org/wiki/Matambwe_language
	https://www.wikidata.org/entity/Q116450240

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Matambwe (wtb-wtb) = 5* (Developing).

[sources]
glottolog = 
	**iso6393:2012-009**
	**iso6393:2020-036**
	**iso6393:2021-037**
	**iso6393:2022-020**

