# -*- coding: utf-8 -*-
[core]
name = Southwest Palawano
hid = plv
level = language
iso639-3 = plv
latitude = 8.67624
longitude = 117.36
macroareas = 
	Papunesia
countries = 
	PH
links = 
	https://www.wikidata.org/entity/Q15614922

[sources]
glottolog = 
	**hh:hv:Thiessen:Palawan**

[altnames]
multitree = 
	Palawano, Southwest
	Philippines
lexvo = 
	Southwest Palawano [en]
hhbib_lgcode = 
	Canipaan Palawan

[identifier]
multitree = plv

[classification]
sub = **hh:hv:Thiessen:Palawan**
subrefs = 
	**hh:hv:Thiessen:Palawan**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Palawano, Southwest (plv-plv) = 5* (Developing).

