# -*- coding: utf-8 -*-
[core]
name = Nomlaki
level = dialect
macroareas = 
	North America
countries = 
	US
iso639-3 = nol
hid = nol

[endangerment]
status = nearly extinct
source = E29
date = 2026-03-17T11:25:25
comment = Nomlaki (nol-nol) = 8b (Nearly extinct). Language of registered tribe: Grindstone Indian Rancheria of Wintun-Wailaki Indians of California, Paskenta Band of Nomlaki Indians of California, Round Valley Indian Tribes-Round Valley Reservation.

[sources]
glottolog = 
	**cldf:gifford:26:1**
	**cldf:goldschmidt:48**
	**cldf:goldschmidt:51**
	**cldf:goldschmidt:66**
	**iso6393:2012-144**

