# -*- coding: utf-8 -*-
[core]
name = Zemgalian
level = dialect
iso639-3 = xzm
hid = xzm
countries = 
	LV
macroareas = 
	Eurasia
timespan = 1575-01-01/1575-01-01
links = 
	https://en.wikipedia.org/wiki/Semigallian_language
	https://www.wikidata.org/entity/Q47631

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Zemgalian (xzm-xzm) = 10 (Extinct).

