# -*- coding: utf-8 -*-
[core]
name = Saweru
hid = swr
level = language
iso639-3 = swr
latitude = -1.91473
longitude = 136.296
macroareas = 
	Papunesia
countries = 
	ID
links = 
	https://www.wikidata.org/entity/Q3474649
	https://en.wikipedia.org/wiki/Saweru_language

[sources]
glottolog = 
	**hh:h:Sugono:Indonesia**
	**hh:hvld:Donohue:WPapuan**
	**hh:hw:Galis:NNG**
	**hh:typ:Donohue:Saweru**
	**hh:w:AyeriDonohue:Saweru**

[altnames]
multitree = 
	Saweroe
	Saweru
lexvo = 
	Saweru [en]
hhbib_lgcode = 
	Basami of Busami-Mariarotu-Kaonda-Kamenab-Krawi certainly related to Turu not Austronesian ?= Saweru

[triggers]
lgcode = 
	saweru

[identifier]
multitree = swr

[endangerment]
status = nearly extinct
source = vanSchie
date = 2026-06-29T11:25:25
comment = Saweru (swr-swr) = 8b (Nearly extinct).

[classification]
sub = **hh:hvs:vanSchie:Papuan-Yapen**:531-552
subrefs = 
	**hh:hvs:vanSchie:Papuan-Yapen**

