# -*- coding: utf-8 -*-
[core]
name = Jorá
hid = jor
level = language
iso639-3 = jor
latitude = -15.7492
longitude = -63.2094
macroareas = 
	South America
countries = 
	BO
links = 
	https://www.wikidata.org/entity/Q5393974
	https://en.wikipedia.org/wiki/Jor%C3%A1_language
timespan = 2000-01-01/2000-01-01

[classification]
sub = **hh:vw:DanielsenGasparini:Jora**
subrefs = 
	**hh:vw:DanielsenGasparini:Jora**

[sources]
glottolog = 
	**hh:ew:Hanke:Jora**
	**hh:hvw:Firestone:Tupi-Guarani**
	**hh:vw:DanielsenGasparini:Jora**
	**hh:w:Loukotka:Inedits**

[altnames]
glottolog = 
	Jora
multitree = 
	Hora
	Jorá
lexvo = 
	Jorá [en]
hhbib_lgcode = 
	Jora

[triggers]
lgcode = 
	kmen
	jezere
	neznamy
	bolivii
	indiansky
	jora

[identifier]
multitree = jor

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Jorá (jor-jor) = 10 (Extinct).

