# -*- coding: utf-8 -*-
[core]
name = Flores
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:113-117
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

