# -*- coding: utf-8 -*-
[core]
name = West Central Maluku
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:369-378
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

