# -*- coding: utf-8 -*-
[core]
name = Northern Toussian
hid = tsp
level = language
iso639-3 = tsp
latitude = 11.133
longitude = -4.88274
macroareas = 
	Africa
countries = 
	BF
links = 
	https://www.wikidata.org/entity/Q11155635
	https://phoible.org/languages/nort2787

[sources]
glottolog = 
	**cldf:prost:ed:64**
	**hh:g:Struthers-Young:Northern-Toussian**
	**hh:s:Zaugg-Coretti:Toussian-Nord**
	**hh:vtyp:Struthers-Young:Toussian**
	**hh:w:Prost:Voltaiques**

[altnames]
multitree = 
	Toussian
	Toussian (Northern)
	Toussian (Southern)
	Toussian, Northern
	Tusia
	Tusian
lexvo = 
	Northern Toussian [en]
hhbib_lgcode = 
	Djigouera Northern Toussian
	Tir
	Toussian N

[triggers]
lgcode = 
	voltaiques AND 342
	toussian

[identifier]
multitree = tsp

[classification]
sub = **hh:typ:Winkelmann:Win**
subrefs = 
	**hh:typ:Winkelmann:Win**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Toussian, Northern (tsp-tsp) = 6a (Vigorous).

