# -*- coding: utf-8 -*-
[core]
name = Bajjika
level = dialect
iso639-3 = vjk
hid = vjk
countries = 
	IN
macroareas = 
	Eurasia
links = 
	https://en.wikipedia.org/wiki/Bajjika
	https://www.wikidata.org/entity/Q3636001

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Bajjika (vjk-vjk) = 5 (Developing).

[sources]
glottolog = 
	**iso6393:2022-004**

