# -*- coding: utf-8 -*-
[core]
name = Laamtuk Thet
hid = tcp
level = language
iso639-3 = tcp
latitude = 22.4996
longitude = 94.0957
macroareas = 
	Eurasia
countries = 
	MM
links = 
	https://en.wikipedia.org/wiki/Thor_language
	https://www.wikidata.org/entity/Q7689338

[sources]
glottolog = 
	**hh:hv:VanBik:Proto-Kuki-Chin**
	**hh:hv:VanBik:Proto-Kuki-Chin:2009**
	**hh:phonvw:Mang:Thor-Hakha**

[altnames]
multitree = 
	Chin, Tawr
	Chin,Tawr
	Tawr
	Torr
lexvo = 
	Tawr Chin [en]
hhbib_lgcode = 
	Chin-Tawr
	Thor

[identifier]
multitree = tcp

[classification]
sub = **hh:hv:Peterson:Kuki-Chin:2017** **hh:hv:VanBik:Proto-Kuki-Chin**
subrefs = 
	**hh:hv:Peterson:Kuki-Chin:2017**
	**hh:hv:VanBik:Proto-Kuki-Chin**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Chin, Tawr (tcp-tcp) = 6a (Vigorous).

