# -*- coding: utf-8 -*-
[core]
name = Kunwinjku
level = dialect
macroareas = 
	Australia
countries = 
links = 
	[Kunwinjku](https://collection.aiatsis.gov.au/austlang/language/n65)
	https://en.wikipedia.org/wiki/Kunwinjku_dialect
	https://phoible.org/languages/guma1252
	https://www.wikidata.org/entity/Q67362494
