# -*- coding: utf-8 -*-
[core]
name = Läoktü Chin
level = language
iso639-3 = cey
hid = cey
countries = 
	MM
macroareas = 
	Eurasia

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Chin, Läoktü (cey-cey) = 6a (Vigorous).

[sources]
glottolog = 
	**hh:soc:Statezni:Dalet**
	**iso6393:2014-061**
	**iso6393:2018-017**

[altnames]
glottolog = 
	Ekai Chin

[classification]
sub = **hh:soc:Statezni:Dalet**
subrefs = 
	**hh:soc:Statezni:Dalet**

