# -*- coding: utf-8 -*-
[core]
name = Kemak-Tukudede
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:255-271 **hh:hv:Edwards:Rote-Meto:2021**:77 **hh:vwphon:Edwards:Welaun** **hh:hvw:Hull:Timor:Austronesian**
subrefs = 
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:vwphon:Edwards:Welaun**
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[altnames]
glottolog = 
	Western Timoric B

