# -*- coding: utf-8 -*-
[core]
name = Batuley-Mariri
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:273-292 **hh:hv:Hughes:Kei-Tanimbar-Aru**:101
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hv:Hughes:Kei-Tanimbar-Aru**

