# -*- coding: utf-8 -*-
[core]
name = Tukudede
hid = tkd
level = language
iso639-3 = tkd
latitude = -8.6788
longitude = 125.283
macroareas = 
	Papunesia
countries = 
	TL
links = 
	https://en.wikipedia.org/wiki/Tokodede_language
	https://www.wikidata.org/entity/Q36863

[sources]
glottolog = 
	**hh:hvw:Capell:Timor**
	**hh:hvw:Hull:Timor:Austronesian**
	**langsci:capell:44**

[altnames]
multitree = 
	Tocod
	Tokodede
	Tokodé
	Tukude
	Tukudede
lexvo = 
	Tukudede [en]
hhbib_lgcode = 
	Tokodede

[identifier]
multitree = tkd

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:255-271 **hh:hv:Edwards:Rote-Meto:2021**:77 **hh:vwphon:Edwards:Welaun** **hh:hvw:Hull:Timor:Austronesian**
subrefs = 
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:vwphon:Edwards:Welaun**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Tukudede (tkd-tkd) = 6a* (Vigorous).

