# -*- coding: utf-8 -*-
[core]
name = Thewo-smad
level = language
macroareas = 
	Eurasia
hid = NOCODE_Thewo-Ma
countries = 
	CN
longitude = 103.93004
latitude = 33.98732

[altnames]
hhbib_lgcode = 
	Dbangbzang
	Dianduo
	Gyiba Tibetan
	Lower Thebo
	Luo Dahua
	Ri-dwangs/Rong-thag
	Ridang
	Ridwags
	Ridwags Tibetan
	Sézanglongwa Tibetan
	Thebo
	Thewo
	Thewo Mä
	Thewo-Ma
	Thewo-Mä
	Wangzang
	dBang-gtsang
	sTeng-ka

[classification]
sub = **hh:hv:TournadreSuzuki:Tibetic**
subrefs = 
	**hh:hv:TournadreSuzuki:Tibetic**

[hh_ethnologue_comment]
comment = The Tibetic varieties of Eastern Thewo are subsumed as a dialect of Choni [cda]
	in E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29. But the varieties of Eastern Thewo are not intelligible
	(**hh:hv:TournadreSuzuki:Tibetic**:500-508, **hh:gv:Yeung:Ridang**:4, 10, 12, 214, 354) with those subsumed under Choni [cda] and thus merit their own entry. See also: Choni [cda].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Thewo-Ma

[sources]
glottolog = 
	**hh:gv:Yeung:Ridang**
	**hh:hvw:Yang:Cone**
	**hh:phon:Jiatso:Sezanglongwa**
	**hh:phon:Lin:Thebo**
	**hh:sv:Renzeng:Diebu**

