# -*- coding: utf-8 -*-
[core]
name = Kakabai linkage
level = family

[classification]
sub = **hh:hv:Ross:WMelanesia**:190-212 **hh:hv:LynchRossCrowley:Subgrouping**:102-106 **hh:g:Sheppard:Sudest**:12
subrefs = 
	**hh:g:Sheppard:Sudest**
	**hh:hv:LynchRossCrowley:Subgrouping**
	**hh:hv:Ross:WMelanesia**

