# -*- coding: utf-8 -*-
[core]
name = Ulat Inai
level = family

[altnames]
multitree = 
	Ulat Inai

[identifier]
multitree = ulat

[classification]
sub = **hh:hvw:Collins:CMaluku** **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:379-439
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hvw:Collins:CMaluku**

