# -*- coding: utf-8 -*-
[core]
name = Nuclear Nunusaku
level = family

[classification]
sub = **hh:hvw:Collins:CMaluku** **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:379-439
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hvw:Collins:CMaluku**

