# -*- coding: utf-8 -*-
[core]
name = Standard Moroccan Tamazight
level = dialect
iso639-3 = zgh
hid = zgh
countries = 
	MA
macroareas = 
	Africa
links = 
	https://en.wikipedia.org/wiki/Standard_Moroccan_Amazigh
	https://www.wikidata.org/entity/Q7598268

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Tamazight, Standard Moroccan (zgh-zgh) = 1 (National). Statutory national language (2011, Constitution, Article 5).

