# -*- coding: utf-8 -*-
[core]
name = Hresuk
level = language
macroareas = 
	Papunesia
countries = 
	TL
hid = NOCODE_Hresuk
longitude = 125.59412
latitude = -8.28319

[altnames]
multitree = 
	Hahak
glottolog = 
	Hahak
hhbib_lgcode = 
	Háhàk
	Makili
	Maquili
	Rêssuk
	SE Atauran

[identifier]
multitree = gal-hah

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:195-202 **hh:hvw:Hull:Timor:Austronesian** **hh:hv:Edwards:Rote-Meto:2021**:77-86
subrefs = 
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hvw:Hull:Timor:Austronesian**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[endangerment]
status = shifting
source = BracksandEdwards
date = 2026-06-01T11:25:25
comment = Hresuk (NOCODE_Hresuk-NOCODE_Hresuk) = 7 (Shifting).

[hh_ethnologue_comment]
comment = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29 includes Hresuk, spoken in the southeast of Atauro island, in a single language Atauran [adb] comprising the Rasua (Rahesuk), Raklungu (Klu’un Hahan Adabe), Hresuk (Resuk) and Dadu’a varieties. In this, the code [adb] is re-used from an entry that originally referred to a supposed Papuan language of Atauro island. However, Hresuk not intelligible to the Rasua, Raklungu and Dadu'a (**hh:hvw:Bracks:Atauro**) and thus merits its own entry. See also: Adabe [adb].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Hresuk

[sources]
glottolog = 
	**hh:d:Duarte:Atauro**
	**hh:e:Duarte:Atauro**
	**hh:ed:Boarccaech:Ressuk**
	**hh:ew:deMagalhaes:Atauro**
	**hh:hvw:Bracks:Atauro**

