# -*- coding: utf-8 -*-
[core]
name = Central East Rote
level = family

[classification]
sub = **hh:hv:Edwards:Rote-Meto:2021** **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:180-188
subrefs = 
	**hh:hv:Edwards:Rote-Meto:2021**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[altnames]
glottolog = 
	Central-Eastern Rote-Meto

