# -*- coding: utf-8 -*-
[core]
name = Ossetic
level = family
links = 
	https://www.wikidata.org/entity/Q33968
	https://en.wikipedia.org/wiki/Ossetian_language

[classification]
sub = **hh:hv:Poulsen:Indo-Iranian-Greek**
subrefs = 
	**hh:hv:Poulsen:Indo-Iranian-Greek**

