# -*- coding: utf-8 -*-
[core]
name = Timor-Babar
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:169-179
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

