# -*- coding: utf-8 -*-
[core]
name = East Rivers Seram
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:441-487
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

