# -*- coding: utf-8 -*-
[core]
name = South Yawa
level = language
macroareas = 
	Papunesia
countries = 
	ID
hid = NOCODE_South-Yawa
longitude = 136.25413
latitude = -1.89487

[altnames]
multitree = 
	South Yawa
hhbib_lgcode = 
	Mariadei
	Tarau
	Toeroe
	Turu

[identifier]
multitree = yva-sou

[classification]
sub = **hh:hvs:vanSchie:Papuan-Yapen**:531-552
subrefs = 
	**hh:hvs:vanSchie:Papuan-Yapen**

[endangerment]
status = moribund
source = vanSchie
date = 2026-06-29T11:25:25
comment = Turu (yva-NOCODE_South-Yawa) = 8a (Moribund).

[hh_ethnologue_comment]
comment = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29 includes the South Yawa varieties (villages Mariadei, Tarau, Turu, Kabuena) in the Yawa [yva] villages, based on the survey of (**hh:hvw:Jones:Yawa**). However, newer, more detailed research has shown that the speech of these villages are not intelligible to all East/North/Central/West Yawa varieties, nor to Saweru [swr] **hh:hvs:vanSchie:Papuan-Yapen**:6-13 and thus merit an entry separate from Central-North Yawa [yva]. See also: Central-North Yawa [yva], Saweru [swr].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_South-Yawa

[sources]
glottolog = 
	**hh:hlde:deClercq:WNNNG**
	**hh:hvs:vanSchie:Papuan-Yapen**
	**hh:hvw:Jones:Yawa**
	**hh:hw:Galis:NNG**
	**hh:hw:SmitsVoorhoeve:Anceaux:B:II**
	**hh:typ:Udimeraa:Onate**

