# -*- coding: utf-8 -*-
[core]
name = Vanga
level = dialect
latitude = 23.8103
longitude = 90.4125
macroareas = 
	Eurasia
countries = 
links = 
	https://en.wikipedia.org/wiki/Dhakaiya_Kutti_dialect
	https://www.wikidata.org/entity/Q48726851

[altnames]
multitree = 
	Vanga

[identifier]
multitree = ben-van

