# -*- coding: utf-8 -*-
[core]
name = Singapore Sign Language
hid = sls
level = language
iso639-3 = sls
latitude = 1.33069
longitude = 103.864
macroareas = 
	Eurasia
countries = 
	SG
links = 
	https://en.wikipedia.org/wiki/Singapore_Sign_Language
	https://www.wikidata.org/entity/Q7512563

[altnames]
multitree = 
	Singapore Sign Language
lexvo = 
	Língua de sinais da Singapura [pt]
	Singapore Sign Language [en]
hhbib_lgcode = 
	Unspecified blend of Shanghainese Sign Language-American Signed Language-Singed Exact English II

[identifier]
multitree = sls

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Singapore Sign Language (sls-sls) = 5 (Developing).

[sources]
glottolog = 
	**hh:hw:Ang:Singapore-Sign**

