# -*- coding: utf-8 -*-
[core]
name = Eastern Dajuic
level = family

[altnames]
multitree = 
	Eastern
	Eastern Daju

[identifier]
multitree = edaj

[classification]
sub = **hh:hvw:Thelwall:Daju**:90-108 **hh:hvw:Thelwall:Daju:1980**:168-172
subrefs = 
	**hh:hvw:Thelwall:Daju**
	**hh:hvw:Thelwall:Daju:1980**

