# -*- coding: utf-8 -*-
[core]
name = Lao Naga
level = language
iso639-3 = nlq
hid = nlq
countries = 
	MM
macroareas = 
	Eurasia
longitude = 95.1937
latitude = 26.42773

[endangerment]
status = threatened
source = E29
date = 2026-03-17T11:25:25
comment = Naga, Lao (nlq-nlq) = 6b (Threatened).

[sources]
glottolog = 
	**hh:hv:Bernhardt:Northern-Naga**
	**hh:hv:vanDam:Patkaian-Northern-Naga**
	**iso6393:2012-049**

[classification]
sub = **hh:hv:vanDam:Patkaian-Northern-Naga** **hh:hv:vanDam:Patkaian** **hh:hv:Burling:NEIndia** **hh:hv:Bernhardt:Northern-Naga**
subrefs = 
	**hh:hv:Burling:NEIndia**
	**hh:hv:vanDam:Patkaian-Northern-Naga**
	**hh:hv:Bernhardt:Northern-Naga**
	**hh:hv:vanDam:Patkaian**

