# -*- coding: utf-8 -*-
[core]
name = Oli-Bidiman
iso639-3 = olb
level = language
latitude = 4.33
longitude = 9.8
macroareas = 
	Africa
countries = 
	CM

[sources]
glottolog = 
	**hh:hb:Dugast:Sud-Cameroun**
	**hh:he:Ardener:Coastal-Cameroons**
	**hh:hv:Nseme:Littoral**
	**hh:hvw:Ebobisse:Sawabantu**
	**hh:hvw:Johnston:Bantu-Semi-Bantu**
	**hh:hvw:Meinhof:Kamerun**
	**hh:phon:Hagege:Wori**
	**hh:phon:Moutome:Bodiman**
	**hh:typ:Ebobisse:Oli**
	**iso6393:2024-009**

[classification]
sub = **hh:hv:NursePhilippson:Bantu**:170 **hh:hvw:Ebobisse:Sawabantu**:395-404 **hh:he:Ardener:Coastal-Cameroons** Yasa-Kombe: **hh:hvw:Ebobisse:Sawabantu**:395-404 **hh:h:Guthrie:Bantu-Western**:26 **hh:soc:Belew:Iyasa**:33
subrefs = 
	**hh:hv:NursePhilippson:Bantu**
	**hh:hvw:Ebobisse:Sawabantu**
	**hh:h:Guthrie:Bantu-Western**
	**hh:he:Ardener:Coastal-Cameroons**
	**hh:soc:Belew:Iyasa**

[altnames]
hhbib_lgcode = 
	Bidiman BID
	Bodiman
	Ewodi
	Oli
	Oli OLI
	Wori
	Wuri

[endangerment]
status = threatened
source = E29
date = 2026-03-17T11:25:25
comment = Oli-Bidiman (olb-olb) = 6b (Threatened).

