# -*- coding: utf-8 -*-
[core]
name = Petun-Wyandot
level = dialect
macroareas = 
	North America
iso639-3 = wyn
hid = wyn
countries = 
	US
timespan = 1960-01-01/1960-01-01

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Wyandot (wyn-wyn) = 9 (Reawakening). Language of registered tribe: Wyandotte Nation.

[sources]
glottolog = 
	**iso6393:2021-041**

