# -*- coding: utf-8 -*-
[core]
name = Kei-Fordata
level = family
links = 
	https://www.wikidata.org/entity/Q30317193

[classification]
sub = **hh:hv:Mills:Tanimbar-Kei** **hh:hv:Blust:CEMP**:276 **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:441-487
subrefs = 
	**hh:hv:Mills:Tanimbar-Kei**
	**hh:hv:Blust:CEMP**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

