# -*- coding: utf-8 -*-
[core]
name = Ngandangara
level = dialect
macroareas = 
	Australia
countries = 
	AU
iso639-3 = ntg
hid = ntg
timespan = 1965-01-01/1965-01-01

[altnames]
multitree = 
	Eromarra
	Ngandangara
	Yarumarra
glottolog = 
	Yarumarra

[identifier]
multitree = nbx-yar

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Ngantangarra (ntg-ntg) = 10 (Extinct).

