# -*- coding: utf-8 -*-
[core]
name = Kurnkopanut
level = dialect
countries = 
	AU
macroareas = 
	Australia
hid = wkr
iso639-3 = wkr

[endangerment]
status = nearly extinct
source = E29
date = 2026-03-17T11:25:25
comment = Keerray-Woorroong (wkr-wkr) = 8b (Nearly extinct).

[altnames]
glottolog = 
	Gunditjmara

[sources]
glottolog = 
	**iso6393:2018-080**

