# -*- coding: utf-8 -*-
[core]
name = Peninsular Eastern Saamic
level = family

[classification]
sub = **hh:hv:Sammallahti:Saami**:6-38
subrefs = 
	**hh:hv:Sammallahti:Saami**

[altnames]
glottolog = 
	Peninsular Eastern Saami

