# -*- coding: utf-8 -*-
[core]
name = Gongvanpounyiu Naga
level = language
iso639-3 = npg
hid = npg
countries = 
	MM
macroareas = 
	Eurasia
longitude = 95.25
latitude = 26.35

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Naga, Ponyo-Gongwang (npg-npg) = 6a (Vigorous).

[sources]
glottolog = 
	**hh:hv:Bernhardt:Northern-Naga**
	**hh:hv:vanDam:Patkaian-Northern-Naga**
	**iso6393:2011-065**

[altnames]
glottolog = 
	Ponyo-Gongwang Naga
	Pounyiu-Gongvan Naga
hhbib_lgcode = 
	Ponyo-Gongwan Naga
	Pounyiu-Gongvan Naga

[classification]
sub = **hh:hvsoc:Wayeshaetal:Lahe** **hh:hv:vanDam:Patkaian** **hh:hv:vanDam:Patkaian-Northern-Naga** **hh:he:Saul:Naga-Burma**
subrefs = 
	**hh:hv:vanDam:Patkaian-Northern-Naga**
	**hh:he:Saul:Naga-Burma**
	**hh:hvsoc:Wayeshaetal:Lahe**
	**hh:hv:vanDam:Patkaian**

