# -*- coding: utf-8 -*-
[core]
name = Wunumara
level = dialect
iso639-3 = wnn
hid = wnn
countries = 
	AU
macroareas = 
	Australia

[endangerment]
status = extinct
source = E29
date = 2026-03-17T11:25:25
comment = Wunumara (wnn-wnn) = 10 (Extinct).

[sources]
glottolog = 
	**iso6393:2012-007**

