# -*- coding: utf-8 -*-
[core]
name = Upper Wallis
level = dialect
macroareas = 
	Eurasia
countries = 

[altnames]
multitree = 
	Wallis
glottolog = 
	Lower Wallis
	Wallis

[identifier]
multitree = gsw-wal

