# -*- coding: utf-8 -*-
[core]
name = East Chadic A.1
level = family
links = 
	https://www.wikidata.org/entity/Q20586106

[classification]
sub = **hh:vwtyp:Jungraithmayr:Gadang**:23-24 **hh:hv:Jungraithmayr:Nachtigal** **hh:hb:BarreteauNewman:Tchadiques**
subrefs = 
	**hh:hv:Jungraithmayr:Nachtigal**
	**hh:hb:BarreteauNewman:Tchadiques**
	**hh:vwtyp:Jungraithmayr:Gadang**

