# -*- coding: utf-8 -*-
[core]
name = Irires
level = language
macroareas = 
	Papunesia
hid = NOCODE_Irires
countries = 
	ID
longitude = 132.9
latitude = -1.15

[altnames]
hhbib_lgcode = 
	Akmuri
	Meinad-Meis-Wafmana-Aifamas
	Meon
	Meyah
	Miun

[classification]
sub = **hh:s:Schapper:Irires**:254
subrefs = 
	**hh:s:Schapper:Irires**

[endangerment]
status = threatened
source = Schapper
date = 2026-05-03T11:25:25
comment = Irires (NOCODE_Irires-NOCODE_Irires) = 6b (Threatened).

[hh_ethnologue_comment]
comment = Irires, an East Bird's Head language, previously assumed to be a dialect of Meyah [mej] (**hh:hw:MiedemaWelling:Kebar**) is, in fact, not intelligible to either Meyah [mej] or Moskona [mtj] (**hh:s:Schapper:Irires**:254) and thus merits its own entry. See also: Meyah [mej], Moskona [mtj].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Irires

