# -*- coding: utf-8 -*-
[core]
name = Bwaidoka-Iduna-Diodio
level = family

[classification]
sub = **hh:hv:Ross:WMelanesia**:190-212 **hh:hvld:Lithgow:Milne**:460
subrefs = 
	**hh:hv:Ross:WMelanesia**
	**hh:hvld:Lithgow:Milne**

