# -*- coding: utf-8 -*-
[core]
name = Karey-Barakai
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:273-292
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

