# -*- coding: utf-8 -*-
[core]
name = Barambo-Pambia-Ngala
level = family
links = 
	https://www.wikidata.org/entity/Q12627595

[altnames]
multitree = 
	Barambo-Pambia
glottolog = 
	Barambo-Pambia

[identifier]
multitree = barp

[classification]
sub = **hh:h:Boyd:Zande**
subrefs = 
	**hh:h:Boyd:Zande**

