# -*- coding: utf-8 -*-
[core]
name = Nipsan
hid = nps
level = language
iso639-3 = nps
latitude = -4.14421
longitude = 139.753
macroareas = 
	Papunesia
countries = 
	ID
links = 
	https://www.wikidata.org/entity/Q11732528
	https://en.wikipedia.org/wiki/Nipsan_language

[sources]
glottolog = 
	**hh:h:SilzerClouse:Index**
	**hh:h:Sugono:Indonesia**

[altnames]
multitree = 
	Nipsan
	Southern Jale
	Yale-Nipsan
	Yali
lexvo = 
	Nipsan [en]
hhbib_lgcode = 
	Mek Nipsan

[identifier]
multitree = nps

[classification]
sub = **hh:hvw:Heeschen:Mek:1978**:9 **hh:sd:Heeschen:Yale**:8
subrefs = 
	**hh:sd:Heeschen:Yale**
	**hh:hvw:Heeschen:Mek:1978**

[endangerment]
status = threatened
source = E29
date = 2026-03-17T11:25:25
comment = Nipsan (nps-nps) = 6b (Threatened).

