# -*- coding: utf-8 -*-
[core]
name = West-Central Flores
level = family

[classification]
sub = **hh:hv:Fernandez:Flores** **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**:117-120
subrefs = 
	**hh:hv:Fernandez:Flores**
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**

[altnames]
glottolog = 
	Flores Barat

