# -*- coding: utf-8 -*-
[core]
name = Russian
hid = rus
level = language
iso639-3 = rus
latitude = 59.0
longitude = 50.0
macroareas = 
	Eurasia
countries = 
	BY
	CN
	EE
	FI
	GE
	KG
	KP
	KZ
	LT
	LV
	MD
	MN
	NO
	PL
	RO
	RU
	SJ
	TM
	UA
	UZ
links = 
	[Russian](https://grambank.clld.org/languages/russ1263)
	[Russian](https://lexibank.clld.org/languages/dunnielex-russian)
	[Russian](https://lexibank.clld.org/languages/northeuralex-rus)
	[Russian](https://lexibank.clld.org/languages/starostinpie-russian)
	[Russian](https://wals.info/languoid/lect/wals_code_rus)
	https://en.wikipedia.org/wiki/Russian_language
	https://phoible.org/languages/russ1263
	https://www.wikidata.org/entity/Q7737

[sources]
glottolog = 
	**anla:ALE904SS1904**
	**anla:CA973K1979d**
	**anla:IN-W-948M1980**
	**anla:KO961K2008**
	**anla:RU008G2008**
	**anla:RU008G2009**
	**anla:RU008G2010**
	**anla:RU961K1996**
	**asjp2010:3901**
	**cldf:alt:alt:59**
	**cldf:babby:brecht:75**
	**cldf:benet:ed:70**
	**cldf:beyer:01:2**
	**cldf:bivon:71**
	**cldf:black:60**
	**cldf:boyanus:55**
	**cldf:comrie:89:1**
	**cldf:corbett:91**
	**cldf:cubberley:02**
	**cldf:dahl:85**
	**cldf:dunn:71:1**
	**cldf:dunn:71:2**
	**cldf:dunn:dunn:63**
	**cldf:dunn:dunn:67**
	**cldf:fainsod:58**
	**cldf:fitzsimmons:ed:57**
	**cldf:fraser:corbett:95**
	**cldf:halle:59**
	**cldf:hamilton:80**
	**cldf:haspelmath:97**
	**cldf:jones:ward:69**
	**cldf:kodzasov:99:2**
	**cldf:krylova:khavronina:76**
	**cldf:launer:74**
	**cldf:mace:mace:63**
	**cldf:mulisch:75**
	**cldf:ovsjannikova:66**
	**cldf:pulkina:78**
	**cldf:pulkina:zakhava-nekrasova:74**
	**cldf:say:66**
	**cldf:schapiro:60**
	**cldf:stilman:harkins:64**
	**cldf:stoll:abboth-smith:etal:66**
	**cldf:stoll:gries:66**
	**cldf:tauscher:kirschbaum:63**
	**cldf:unbegaun:57**
	**cldf:wade:92**
	**cldf:wedel:romanov:64**
	**cldf:winawer:07**
	**hh:dial:Grinkova:Voronezhskie**
	**hh:g:Berneker:Russische**
	**hh:g:BernekerVasmer:Russische**
	**hh:g:BorrasChristian:Russian**
	**hh:g:DunnKhairov:Russian**
	**hh:g:Gluck:Russischen**
	**hh:g:Houtzagers:Russische**
	**hh:g:Morfill:Russian**
	**hh:g:Shvedova:Russkaya**
	**hh:g:Timberlake:Russian**
	**hh:g:Wade:Russian**
	**hh:g:Wade:Russian:2020**
	**hh:hld:Liu:Eluosi**
	**hh:hld:ShearerHongkai:China**
	**hh:hv:SussexCubberley:Russian**
	**hh:ld:Verschik:Jewish-Russian**
	**hh:ldsoc:Golovko:Russian-America**
	**hh:phon:Harshenin:Dukhobor**
	**hh:s:Andrews:Russian**
	**hh:s:Kantarovich:Ninilchik-Russian**
	**hh:s:Ludolf:Russica**
	**hh:soc:Daly:Alaskan-Russian**
	**hh:typ:Babby:Russian**
	**hh:typ:Bai:Eluosi**
	**hh:typ:BergelsonKibrik:Ninilchik-Russian**
	**hh:typ:Daly:Alaskan-Russian**
	**hh:typ:Krupp:Russian**
	**hh:typ:Leisio:Finland-Russian**
	**hh:typ:Steriopolo:Ninilchik-Russian**
	**hh:vldsoc:Bergelson:Lost-Russian**
	**ldh:item_400292**
	**ldh:item_400517**
	**ldh:item_403305**
	**ldh:item_404229**
	**ldh:item_404466**
	**ldh:item_405118**
	**ldh:item_405848**
	**ldh:item_406127**
	**mpieva:1959Antologi**
	**mpieva:1985Issuesin**
	**mpieva:Ajgi1971Beginnde**
	**mpieva:Ajtmatov1970Beyazgem**
	**mpieva:Amit1973Silneelj**
	**mpieva:Andrews2001Russian**
	**mpieva:Appel1996Textsort**
	**mpieva:Asmarin1968Thesauru**
	**mpieva:Azarch1984Slovoobr**
	**mpieva:Baguslawski2003Aspektin**
	**mpieva:Baskakov1953Chakassk**
	**mpieva:Baskakov1956RyscaTur**
	**mpieva:Baskakov1967Russakar**
	**mpieva:Baskakov1968Turkmenc**
	**mpieva:Bermel1997Contexta**
	**mpieva:Blokland2005TheRussi**
	**mpieva:Boldyrev1994RusskoEv**
	**mpieva:Borik2002Aspectan**
	**mpieva:Borik2006Aspectan**
	**mpieva:BornRauchenecker2001Temporal**
	**mpieva:Brown1999Thesynta**
	**mpieva:Burkhardt1990ModaleFu**
	**mpieva:Cankov1961Russkoch**
	**mpieva:Cholodovic1951Korejsko**
	**mpieva:Chuzangaj1976Zdravstv**
	**mpieva:Comrie1996TheRussi**
	**mpieva:Cooper2003Ofcabbag**
	**mpieva:Cubberley2002Russiana**
	**mpieva:Cydendambaev1962Kratkijr**
	**mpieva:DambaRincine1960Russkijm**
	**mpieva:Domozakov1974Vdalekom**
	**mpieva:Dunn2008ModernRu**
	**mpieva:DurstAndersen1992Mentalgr**
	**mpieva:Forsyth1970Agrammar**
	**mpieva:Galkin1966Russkoma**
	**mpieva:Grenoble1998Deixisan**
	**mpieva:Haarmann1984Soziolin**
	**mpieva:Hacking1998Codingth**
	**mpieva:Halle1971Thesound**
	**mpieva:Hansen2001Dasslavi**
	**mpieva:Hohlig1997Kontaktb**
	**mpieva:HuttlFolter1963Foreignw**
	**mpieva:Ibragimov1952Nastupit**
	**mpieva:Kalima1910Dierussi**
	**mpieva:Kalima1919DieOstse**
	**mpieva:Kallestinova2007Aspectso**
	**mpieva:Kalman1961Dierussi**
	**mpieva:Katanov1963Chakassk**
	**mpieva:Kerbabajev1950Ajsoltan**
	**mpieva:King1995Configur**
	**mpieva:Klenin1983Animacyi**
	**mpieva:Koci1951Kratkija**
	**mpieva:Koljadenkov1948Russkoer**
	**mpieva:Koljadenkov1949Erzjansk**
	**mpieva:Kresin1994Thirdper**
	**mpieva:Kukkonen1955Suomalai**
	**mpieva:Lagerberg1999Stressan**
	**mpieva:Laitin1998Identity**
	**mpieva:Lindseth1998Nullsubj**
	**mpieva:Luvsandendev1957Mongolor**
	**mpieva:Melvold1990Structur**
	**mpieva:Mitchell1997Empathya**
	**mpieva:Mongus1980OrusTyva**
	**mpieva:Mozolkov1940Dzangrka**
	**mpieva:Nadzip1979Istoriko**
	**mpieva:Neidle1988Theroleo**
	**mpieva:Neikirk1996Fromadap**
	**mpieva:Nemzer1951Japonsko**
	**mpieva:Nichols1981Predicat**
	**mpieva:Nuckols2007Casevari**
	**mpieva:Olderogge1963Chausaru**
	**mpieva:Palmbach1953Orustyva**
	**mpieva:Panzer1978Dergenet**
	**mpieva:Pirojkov2002Russizis**
	**mpieva:Pjatigarskij1960Tamilsko**
	**mpieva:Poupynin1999Interact**
	**mpieva:Rachimov1956Ruscauyg**
	**mpieva:Radloff1960Versuche**
	**mpieva:Rappaport1984Grammati**
	**mpieva:Rodina2007Semantic**
	**mpieva:Rodionova2001Wordorde**
	**mpieva:Ruzicka1980Studienz**
	**mpieva:RyazanovaClarke1999TheRussi**
	**mpieva:Sarychanov1951Rasskazy**
	**mpieva:Schlegel1999ZurRolle**
	**mpieva:Schlegel2000Deraspek**
	**mpieva:Schoorlemmer1995Particip**
	**mpieva:Seo2001Thefrequ**
	**mpieva:Shapiro1968Russianp**
	**mpieva:Siloussar2007Grammara**
	**mpieva:Sirotkin1961Cuvassko**
	**mpieva:Stoll2001Theacqui**
	**mpieva:Tmenova2000Osetinsk**
	**mpieva:Townsend1996Commonan**
	**mpieva:Unbegaun1962Russiang**
	**mpieva:Usatov1951Russkoko**
	**mpieva:Vachrusev1956Russkoud**
	**mpieva:Vasilevic1958Evenkijs**
	**mpieva:Vasmer1976Russisch**
	**mpieva:Veenker1997DieFrage**
	**mpieva:Vladimircov1923Mongoloo**
	**mpieva:Vonen1997Partsofs**
	**mpieva:Zaliznjak1980Grammati**
	**mpieva:Zaliznjak2002Russkoei**
	**mpieva:Zybatow1995Russisch**
	**sil16:51141**

[altnames]
wals = 
	Russian
ruhlen (1987) = 
	Russian
moseley & asher (1994) = 
	Russian
multitree = 
	Eluosi
	Great Russian
	Olossu
	Russ
	Russian
	Russisch
	Russit
	Russki
lexvo = 
	Bahasa Rusia [id]
	Basa Rusia [jv]
	Biʼééʼ Łichííʼí bizaad [nv]
	Errusiera [eu]
	Fiteny rosy [mg]
	Gjuha ruse [sq]
	Idioma ruso [an]
	IsiRashiya [zu]
	Język rosyjski [pl]
	Kirusi [sw]
	Krievu valoda [lv]
	Lang ris [ht]
	Lenga russa [pms]
	Lengua russa [lij]
	Limba rusă [ro]
	Lingua Russica [la]
	Lingua rusa [gl]
	Lingua russa [co]
	Lingua russe [ia]
	Lingua ruśa [lad]
	Língua russa [pt]
	Lō͘-se-a-gí [nan]
	Ngò-ngî [hak]
	Orosz nyelv [hu]
	Rinuso [ceb]
	Rinusyan [war]
	Rooshish [gv]
	Rosu kalba [lt]
	Roushie leid [sco]
	Ruiseis [gd]
	Ruoššagiella [se]
	Rus [ca]
	Rus dili [az]
	Rus tili [crh]
	Rusa lingvo [eo]
	Rushan [pih]
	Rusiana linguo [io]
	Rusianeg [br]
	Rusikani chhib [rom]
	Ruski [diq]
	Ruski jezik [bs]
	Rusko godka [szl]
	Ruso [bcl]
	Rusojska rěc [dsb]
	Russe [fr]
	Russek [kw]
	Russesch [lb]
	Russi bhasa [hif]
	Russian [en]
	Russian language [en]
	Russies [af]
	Russisc sprǣc [ang]
	Russisch [li]
	Russische Sprache [de]
	Russisk [da]
	Russisk språk [nn]
	Russo [frp]
	Russysk [fy]
	Russ’sche Spraak [nds]
	Rusu [ast]
	Rusu simi [qu]
	Rusça [tr]
	Rusų kalba [lt]
	Ruština [cs]
	Rušćina [hsb]
	Ruščina [sl]
	Rwseg [cy]
	Ryska [sv]
	Rúisis [ga]
	Rússneska [is]
	Rüss [lmo]
	Tiếng Nga [vi]
	Tok Rasia [tpi]
	Urıs tele [tt]
	Vene keel [et]
	Venäjän kieli [fi]
	Vinne kiil [vro]
	Wikang Ruso [tl]
	Zimanê rûsî [ku]
	rukybau [jbo]
	russe [fr]
	Èdè Rọ́síà [yo]
	Ρωσική γλώσσα [el]
	Вырăс чĕлхи [cv]
	ГІурус мацI [av]
	Забони Русӣ [tg]
	Нуучча тыла [sah]
	Ород хэлэн [bxr]
	Орос хэл [mn]
	Орсин келн [xal]
	Орус тили [ky]
	Орыс тілі [kk]
	Оьрус маз [lbe]
	Расейская мова [be]
	Російська мова [uk]
	Роу́сьскъ ѩꙁꙑ́къ [cu]
	Роч кыв [kv]
	Рузонь кель [myv]
	Рузонь кяль [mdf]
	Руская мова [be]
	Руски език [bg]
	Руски јазик [mk]
	Руски језик [sr]
	Русский язык [ru]
	Руш йылме [mhr]
	Урыҫ теле [ba]
	Уырыссаг æвзаг [os]
	Ӟуч кыл [udm]
	Ռուսերեն [hy]
	רוסיש [yi]
	רוסית [he]
	روسى [arz]
	روسی [pnb]
	رۇس تىلى [ug]
	زبان روسی [fa]
	زمانی ڕووسی [ckb]
	لغة روسية [ar]
	ܠܫܢܐ ܪܘܣܝܐ [aii]
	ރޫސީ [dv]
	रशियन भाषा [mr]
	रूसी भाषा [hi]
	রুশ ভাষা [bn]
	ਰੂਸੀ ਭਾਸ਼ਾ [pa]
	உருசிய மொழி [ta]
	ರಷ್ಯಾದ ಭಾಷೆ [kn]
	റഷ്യൻ ഭാഷ [ml]
	ภาษารัสเซีย [th]
	ཨུ་རུ་སུའི་སྐད། [bo]
	რუსული ენა [ka]
	ភាសារុស្ស៊ី [km]
	ロシア語 [ja]
	俄文 [yue]
	俄語 [gan]
	俄語 [lzh]
	俄语 [wuu]
	러시아어 [ko]
	𐍂𐌿𐍃𐌰𐍂𐌰𐌶𐌳𐌰 [got]
hhbib_lgcode = 
	Alaskan Russian
	Dukhobor
	Eluosi
	Jewish Russian
	Kodiak Creole Russian
	Kyyröla Russian
	Nei Menggu Eluosi
	Ninilchik Russian
	Voronezhskie

[triggers]
lgcode = 
	russizismen
	venalainen
	russica
	zdravstvuj
	russicae
	perestrojka
	dalekom
	russischen
	russisches
	posle
inlg = 
	v
	jazyk
	yazyk
	jazyka
	yazyka
	slov
	iazyke
	okolo
	jazykach
	jazyke
	yazyki

[identifier]
wals = rus
multitree = rus
languagelandscape = http://languagelandscape.org/language/Russian

[classification]
sub = **hh:hvtyp:SussexCubberley:Slavic** **hh:hv:Poljakov:Slavic**
subrefs = 
	**hh:hvtyp:SussexCubberley:Slavic**
	**hh:hv:Poljakov:Slavic**

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Russian (rus-rus) = 1 (National). Statutory national language (1993, Constitution, Article 68(1)). Provincially recognized language in Dagestan Autonomous Republic (1994, Constitution of Dagestan Autonomous Republic, Article 10).

