# -*- coding: utf-8 -*-
[core]
name = Hunsrik
hid = hrx
level = language
iso639-3 = hrx
macroareas = 
	South America
countries = 
	BR
links = 
	https://en.wikipedia.org/wiki/Hunsrik
	https://www.wikidata.org/entity/Q304049
longitude = -51.7219
latitude = -29.3255

[sources]
glottolog = 
	**hh:h:Rosenberg:Lateinamerika**
	**hh:phon:Wiesemann:Hunsrik**
	**hh:phonsocv:Altenhofen:Hunsruckisch**
	**iso6393:2006-037**

[altnames]
multitree = 
	Hunsrik
	Hunsriker
	Rio Grand Hunsriker
	Riograndenser Hunsrückisch
lexvo = 
	Hunsrik [en]
	Riograndenser Hunsrückisch [de]
	Riograndeser Hunsrückisch [pl]
hhbib_lgcode = 
	Brazilien
	Hunsrückisch

[triggers]
lgcode = 
	hunsrik
	ursula

[identifier]
multitree = hrx

[classification]
sub = **hh:hv:Wiesinger:Deutschen**:846-849
subrefs = 
	**hh:hv:Wiesinger:Deutschen**

[endangerment]
status = shifting
source = E29
date = 2026-03-17T11:25:25
comment = Hunsrik (hrx-hrx) = 7 (Shifting).

