# -*- coding: utf-8 -*-
[core]
name = Mekeo-Kuni
level = family

[classification]
sub = **hh:hv:Ross:WMelanesia**:190-212 **hh:g:Jones:Mekeo**:23-25
subrefs = 
	**hh:g:Jones:Mekeo**
	**hh:hv:Ross:WMelanesia**

