# -*- coding: utf-8 -*-
[core]
name = Oninic
level = family

[classification]
sub = **hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia** **hh:hv:Kaplan:Onin-Sekar-Uruangnirin**
subrefs = 
	**hh:hv:GrimesEdwards:Austronesian-Eastern-Indonesia**
	**hh:hv:Kaplan:Onin-Sekar-Uruangnirin**

