# -*- coding: utf-8 -*-
[core]
name = Yawa-Saweru
level = family
links = 
	https://www.wikidata.org/entity/Q3217545
	https://en.wikipedia.org/wiki/Yawa_languages

[identifier]
wals = genus/yawa

[classification]
familyrefs = 
	**hh:hvs:vanSchie:Papuan-Yapen**
sub = **hh:hvs:vanSchie:Papuan-Yapen**:531-552
subrefs = 
	**hh:hvs:vanSchie:Papuan-Yapen**

