# -*- coding: utf-8 -*-
[core]
name = Nuta
level = family

[altnames]
multitree = 
	Bomberai
glottolog = 
	Arguni-Darembang
	Bomberai

[identifier]
multitree = bomb

[classification]
sub = **hh:vw:Jacobson:Nuta**
subrefs = 
	**hh:vw:Jacobson:Nuta**

