# -*- coding: utf-8 -*-
[core]
name = Gerai
level = dialect
macroareas = 
	Papunesia
countries = 
	ID
iso639-3 = gef
hid = gef
links = 
	https://en.wikipedia.org/wiki/Gerai_language
	https://www.wikidata.org/entity/Q24841855

[altnames]
multitree = 
	Gerai

[identifier]
multitree = sdm-ger

[endangerment]
status = not endangered
source = E29
date = 2026-03-17T11:25:25
comment = Gerai (gef-gef) = 5 (Developing).

[sources]
glottolog = 
	**iso6393:2019-043**

