# -*- coding: utf-8 -*-
[core]
name = Thar Bede
level = language
hid = NOCODE_Thar-Bede

[altnames]
hhbib_lgcode = 
	a speech register of Bengali

[sources]
glottolog = 
	**hh:wtyp:Rahman:Thar-Bede**

